Repository dvanoni/notero, pull requests merged in 2022-11, with the labels that each got.

#101 feat: Enable customization of field to use as Notion page title
  README.md
  content/notero-item.ts
  content/notero-pref.ts
  content/notero.ts
  content/notion.ts
  content/preferences.ts
  content/preferences.xul
  content/utils.ts
  content/utils/buildCollectionFullName.ts
  content/utils/getLocalizedString.ts
  content/utils/getXULElementById.ts
  content/utils/hasErrorStack.ts
  content/utils/index.ts
  defaults/preferences/notero.js
  locale/en-US/notero.dtd
  locale/en-US/notero.properties
  locale/zh-CN/notero.dtd
  locale/zh-CN/notero.properties
  typings/xpcom.d.ts
  typings/xul.d.ts
  typings/zotero.d.ts
Labels: enhancement

#129 Update Readme with new Notion integration UI
  README.md
  docs/share-with-notero.png
Labels: documentation

#174 build(deps): Upgrade dependencies
  package-lock.json
  package.json
Labels: dependencies

#183 build(deps): Upgrade dependencies
  package-lock.json
  package.json
Labels: dependencies
